debug: true

jobs:
  - subnet: '10.10.0.0/23'
    config_file: '/home/mortimor/monitoring/config/telegraf/telegraf-ping.conf'
    container_name: 'telegraf-ping'
  - subnet: '10.12.0.0/24'
    config_file: '/home/mortimor/monitoring/config/telegraf/telegraf-ping.conf'
    container_name: 'telegraf-ping'
  - subnet: '10.10.0.0/23'
    config_file: '/home/mortimor/monitoring/config/telegraf/telegraf-snmp-interface2.conf'
    container_name: 'telegraf-snmp-interface2'